# Generated by Django 4.2.4 on 2023-08-31 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingmessage',
            name='settings',
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingmessage'),
        ),
        migrations.AlterField(
            model_name='mailinglogs',
            name='settigns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingmessage'),
        ),
        migrations.AlterField(
            model_name='mailingmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема'),
        ),
    ]
