# Generated by Django 4.2.4 on 2023-09-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='time',
            field=models.TimeField(verbose_name='Время рассылки'),
        ),
    ]
