# Generated by Django 4.2.4 on 2023-09-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailingsettings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmessage',
            name='message',
            field=models.TextField(default=1, verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingmessage',
            name='subject',
            field=models.CharField(default=1, max_length=200, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
