# Generated by Django 4.2.4 on 2023-08-31 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailingmessage_setting_alter_mailingsettings_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingmessage',
            old_name='setting',
            new_name='settings',
        ),
        migrations.AlterField(
            model_name='mailinglogs',
            name='settigns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings'),
        ),
    ]
