# Generated by Django 4.2.4 on 2023-09-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='last_sent',
            field=models.DateTimeField(auto_now=True, verbose_name='Время до отправки'),
        ),
    ]
