# Generated by Django 4.2.4 on 2023-09-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailingsettings_last_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время до отправки'),
        ),
    ]
