# Generated by Django 4.2.4 on 2023-09-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailingsettings_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='message',
        ),
    ]
