# Generated by Django 4.2.4 on 2023-09-01 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_remove_mailingsettings_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmessage',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings'),
        ),
    ]
